// <auto-generated />
using System;
using BillPaymentSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillPaymentSystem.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20240416224021_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillPaymentSystem.Models.DataModel+Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Month")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberId");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPaid = true,
                            Month = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 1,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 2,
                            IsPaid = false,
                            Month = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 1,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 3,
                            IsPaid = true,
                            Month = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 2,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 4,
                            IsPaid = false,
                            Month = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 2,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 5,
                            IsPaid = false,
                            Month = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 3,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 6,
                            IsPaid = true,
                            Month = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 3,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 7,
                            IsPaid = false,
                            Month = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 4,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 8,
                            IsPaid = true,
                            Month = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 4,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 9,
                            IsPaid = false,
                            Month = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 5,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 10,
                            IsPaid = true,
                            Month = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 5,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 11,
                            IsPaid = false,
                            Month = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 6,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 12,
                            IsPaid = true,
                            Month = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 6,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 13,
                            IsPaid = false,
                            Month = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 7,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 14,
                            IsPaid = true,
                            Month = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 7,
                            TotalAmount = 260m
                        },
                        new
                        {
                            Id = 15,
                            IsPaid = true,
                            Month = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 7,
                            TotalAmount = 260m
                        });
                });

            modelBuilder.Entity("BillPaymentSystem.Models.DataModel+Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubscriberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubscriberNo = "10"
                        },
                        new
                        {
                            Id = 2,
                            SubscriberNo = "20"
                        },
                        new
                        {
                            Id = 3,
                            SubscriberNo = "30"
                        },
                        new
                        {
                            Id = 4,
                            SubscriberNo = "40"
                        },
                        new
                        {
                            Id = 5,
                            SubscriberNo = "50"
                        },
                        new
                        {
                            Id = 6,
                            SubscriberNo = "60"
                        },
                        new
                        {
                            Id = 7,
                            SubscriberNo = "70"
                        });
                });

            modelBuilder.Entity("BillPaymentSystem.Models.DataModel+Bill", b =>
                {
                    b.HasOne("BillPaymentSystem.Models.DataModel+Subscriber", "Subscriber")
                        .WithMany("Bills")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("BillPaymentSystem.Models.DataModel+Subscriber", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
